import GarblingPrize.Protected.Target

open scoped BigOperators

namespace GarblingPrize.Submission.DRE

variable {ι R : Type*} [Fintype ι] [CommRing R]

/-- Reconstruction of a component vector using its public component weights. -/
def weightedSum (weights values : ι → R) : R :=
  ∑ i, weights i * values i

/-- The hidden-mask fiber consists exactly of component vectors having weighted sum zero. -/
def WeightedZeroMask (weights : ι → R) : Type _ :=
  {mask : ι → R // weightedSum weights mask = 0}

/-- Add an unmasked active value and its hidden mask at every component. -/
def decodedComponents (weights unmasked : ι → R) (mask : WeightedZeroMask weights) : ι → R :=
  fun i => unmasked i + mask.1 i

/-- Native reconstruction is the public weighted sum of all decoded components. -/
def nativeReconstruction (weights decoded : ι → R) : R :=
  weightedSum weights decoded

/-- The complete active view: public weights, the ordered decoded vector, and its output. -/
structure ActiveView (ι R : Type*) where
  weights : ι → R
  decoded : ι → R
  output : R

/-- Construct the complete active view generated by an unmasked vector and a valid mask. -/
def completeActiveView (weights unmasked : ι → R) (mask : WeightedZeroMask weights) :
    ActiveView ι R :=
  ⟨weights, decodedComponents weights unmasked mask,
    nativeReconstruction weights (decodedComponents weights unmasked mask)⟩

/-- A valid hidden mask reconstructs to precisely the unmasked weighted sum. -/
theorem nativeReconstruction_decodedComponents
    (weights unmasked : ι → R) (mask : WeightedZeroMask weights) :
    nativeReconstruction weights (decodedComponents weights unmasked mask) =
      weightedSum weights unmasked := by
  simp only [nativeReconstruction, decodedComponents, weightedSum, mul_add,
    Finset.sum_add_distrib]
  rw [show (∑ i, weights i * mask.1 i) = weightedSum weights mask.1 by rfl,
    mask.property]
  simp

/-- Translate a source mask for use with a target unmasked vector. -/
def translateMask (weights source target : ι → R)
    (h : weightedSum weights source = weightedSum weights target)
    (mask : WeightedZeroMask weights) : WeightedZeroMask weights :=
  ⟨fun i => mask.1 i + source i - target i, by
    simp only [weightedSum, mul_sub, mul_add, Finset.sum_sub_distrib,
      Finset.sum_add_distrib]
    rw [show (∑ i, weights i * mask.1 i) = weightedSum weights mask.1 by rfl,
      mask.property]
    change 0 + weightedSum weights source - weightedSum weights target = 0
    rw [h]
    simp⟩

/-- Translation makes every target decoded component equal its source counterpart. -/
theorem decodedComponents_translateMask
    (weights source target : ι → R)
    (h : weightedSum weights source = weightedSum weights target)
    (mask : WeightedZeroMask weights) :
    decodedComponents weights target (translateMask weights source target h mask) =
      decodedComponents weights source mask := by
  funext i
  simp [decodedComponents, translateMask]
  ring

/-- Translating from source to target and back is the identity. -/
theorem translateMask_source_target_source
    (weights source target : ι → R)
    (h : weightedSum weights source = weightedSum weights target)
    (mask : WeightedZeroMask weights) :
    translateMask weights target source h.symm
      (translateMask weights source target h mask) = mask := by
  apply Subtype.ext
  funext i
  simp [translateMask]

/-- Translating from target to source and back is the identity. -/
theorem translateMask_target_source_target
    (weights source target : ι → R)
    (h : weightedSum weights source = weightedSum weights target)
    (mask : WeightedZeroMask weights) :
    translateMask weights source target h
      (translateMask weights target source h.symm mask) = mask := by
  apply Subtype.ext
  funext i
  simp [translateMask]

/-- Equal-weighted-sum unmasked vectors have explicitly equivalent mask fibers. -/
def weightedZeroMaskEquiv
    (weights source target : ι → R)
    (h : weightedSum weights source = weightedSum weights target) :
    WeightedZeroMask weights ≃ WeightedZeroMask weights where
  toFun := translateMask weights source target h
  invFun := translateMask weights target source h.symm
  left_inv := translateMask_source_target_source weights source target h
  right_inv := translateMask_target_source_target weights source target h

/-- Mask-fiber translation preserves the complete active view, field for field. -/
theorem completeActiveView_weightedZeroMaskEquiv
    (weights source target : ι → R)
    (h : weightedSum weights source = weightedSum weights target)
    (mask : WeightedZeroMask weights) :
    completeActiveView weights target (weightedZeroMaskEquiv weights source target h mask) =
      completeActiveView weights source mask := by
  change completeActiveView weights target (translateMask weights source target h mask) =
    completeActiveView weights source mask
  unfold completeActiveView
  rw [decodedComponents_translateMask]

end GarblingPrize.Submission.DRE
